-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 12:35:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `IDUsuario` INT NOT NULL,
  `NombreUsu` VARCHAR(45) NOT NULL,
  `ClaveUsu` VARCHAR(45) NOT NULL,
  `Cargo` INT NOT NULL,
  PRIMARY KEY (`IDUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `IDCarrera` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Egresado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Egresado` (
  `CI` INT NOT NULL,
  `NombreEgresado` VARCHAR(45) NOT NULL,
  `ApellidoEgresado` VARCHAR(45) NOT NULL,
  `Tlf` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `FechaNacim` DATE NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  `preguntaSeg` VARCHAR(45) NOT NULL,
  `Usuario_IDUsuario` INT NOT NULL,
  `Carrera_IDCarrera` INT NOT NULL,
  PRIMARY KEY (`CI`, `Usuario_IDUsuario`, `Carrera_IDCarrera`),
  UNIQUE INDEX `FechaNacim_UNIQUE` (`FechaNacim` ASC),
  INDEX `fk_Egresado_Usuario1_idx` (`Usuario_IDUsuario` ASC),
  INDEX `fk_Egresado_Carrera1_idx` (`Carrera_IDCarrera` ASC),
  CONSTRAINT `fk_Egresado_Usuario1`
    FOREIGN KEY (`Usuario_IDUsuario`)
    REFERENCES `mydb`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Egresado_Carrera1`
    FOREIGN KEY (`Carrera_IDCarrera`)
    REFERENCES `mydb`.`Carrera` (`IDCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatosEgresado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatosEgresado` (
  `CIEgresado` INT NOT NULL,
  `CorreoUCAB` VARCHAR(45) NOT NULL,
  `AñoIngreso` INT NOT NULL,
  `AñoEgreso` INT NOT NULL,
  `Eficiencia1` TINYINT NOT NULL,
  PRIMARY KEY (`CIEgresado`),
  CONSTRAINT `CIEgresado`
    FOREIGN KEY (`CIEgresado`)
    REFERENCES `mydb`.`Egresado` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `IDCargo` INT NOT NULL,
  `NombreCargo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PeriodoElectoral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PeriodoElectoral` (
  `IDPE` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `FechaIP` DATE NOT NULL,
  `FechaFP` DATE NOT NULL,
  `FechaIV` DATE NOT NULL,
  `FechaFV` DATE NOT NULL,
  `Estado` ENUM('I', 'P', 'C') NOT NULL,
  PRIMARY KEY (`IDPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Postulacion` (
  `IDPostulacion` INT NOT NULL PRIMARY KEY,
  `CIEgresado` INT NOT NULL,
  `IDPE1` INT NOT NULL,
  `IDCargo1` INT NOT NULL,
  `ValidadaEscuela` TINYINT NOT NULL,
  `ValidadaCE` TINYINT NOT NULL,
  `Escalafon` VARCHAR(45) NOT NULL,
  `Fotografia` VARCHAR(45) NOT NULL,


    FOREIGN KEY (`CIEgresado`)
    REFERENCES `mydb`.`Egresado` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,


    FOREIGN KEY (`IDPE1`)
    REFERENCES `mydb`.`PeriodoElectoral` (`IDPE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,


    FOREIGN KEY (`IDCargo1`)
    REFERENCES `mydb`.`Cargo` (`IDCargo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RetiroPostulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RetiroPostulacion` (
  `IDRetiro` INT NOT NULL,
  `IDPostulacion` INT NOT NULL,
  `Causa` VARCHAR(45) NOT NULL,
  `FechaRetiro` DATE NOT NULL,
  PRIMARY KEY (`IDRetiro`),
  INDEX `IDPostulacion_idx` (`IDPostulacion` ASC),
  CONSTRAINT `IDPostulacion`
    FOREIGN KEY (`IDPostulacion`)
    REFERENCES `mydb`.`Postulacion` (`IDPostulacion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PapeletaElectoral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PapeletaElectoral` (
  `IDPapeleta` INT NOT NULL,
  `IDPE` INT NOT NULL,
  `IDPostulacion` INT NOT NULL,
  `IDCargo` INT NOT NULL,
  PRIMARY KEY (`IDPapeleta`),
  INDEX `IDPE_idx` (`IDPE` ASC),
  INDEX `IDPostulacion_idx` (`IDPostulacion` ASC),
  INDEX `IDCargo_idx` (`IDCargo` ASC),

    FOREIGN KEY (`IDPE`)
    REFERENCES `mydb`.`PeriodoElectoral` (`IDPE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,

    FOREIGN KEY (`IDPostulacion`)
    REFERENCES `mydb`.`Postulacion` (`IDPostulacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

    FOREIGN KEY (`IDCargo`)
    REFERENCES `mydb`.`Cargo` (`IDCargo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Votacion` (
  `idVotacion` INT NOT NULL,
  `IDPE` INT NULL,
  `IDPostulacion` INT NULL,
  `TotalVotos` INT NULL,
  PRIMARY KEY (`idVotacion`),
  INDEX `IDPE_idx` (`IDPE` ASC),
  INDEX `IDPostulacion_idx` (`IDPostulacion` ASC),

    FOREIGN KEY (`IDPE`)
    REFERENCES `mydb`.`PeriodoElectoral` (`IDPE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,

    FOREIGN KEY (`IDPostulacion`)
    REFERENCES `mydb`.`Postulacion` (`IDPostulacion`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GanadorEleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GanadorEleccion` (
  `CIEgresado` INT NOT NULL,
  `IDPE` INT NOT NULL,
  `IDCargo` INT NOT NULL,
  PRIMARY KEY (`CIEgresado`, `IDPE`, `IDCargo`),
  CONSTRAINT `IDPE`
    FOREIGN KEY (`IDPE`)
    REFERENCES `mydb`.`PeriodoElectoral` (`IDPE`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `CI`
    FOREIGN KEY (`CIEgresado`)
    REFERENCES `mydb`.`Egresado` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `IDCargo`
    FOREIGN KEY (`IDCargo`)
    REFERENCES `mydb`.`Cargo` (`IDCargo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CargosxCarrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CargosxCarrera` (
  `Carrera_IDCarrera` INT NOT NULL,
  `Cargo_IDCargo` INT NOT NULL,
  `PeriodoElectoral_IDPE` INT NOT NULL,
  `Conformado` TINYINT NOT NULL,
  PRIMARY KEY (`Carrera_IDCarrera`, `Cargo_IDCargo`, `PeriodoElectoral_IDPE`),
  INDEX `fk_CargosxCarrera_Cargo1_idx` (`Cargo_IDCargo` ASC),
  INDEX `fk_CargosxCarrera_PeriodoElectoral1_idx` (`PeriodoElectoral_IDPE` ASC),
  CONSTRAINT `fk_CargosxCarrera_Carrera1`
    FOREIGN KEY (`Carrera_IDCarrera`)
    REFERENCES `mydb`.`Carrera` (`IDCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CargosxCarrera_Cargo1`
    FOREIGN KEY (`Cargo_IDCargo`)
    REFERENCES `mydb`.`Cargo` (`IDCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CargosxCarrera_PeriodoElectoral1`
    FOREIGN KEY (`PeriodoElectoral_IDPE`)
    REFERENCES `mydb`.`PeriodoElectoral` (`IDPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PropuestaCampaña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PropuestaCampaña` (
  `IDPC` INT NOT NULL AUTO_INCREMENT,
  `Postulacion_IDPostulacion` INT NOT NULL,
  `prpuesta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPC`),
  INDEX `fk_PropuestaCampaña_Postulacion1_idx` (`Postulacion_IDPostulacion` ASC),
  CONSTRAINT `fk_PropuestaCampaña_Postulacion1`
    FOREIGN KEY (`Postulacion_IDPostulacion`)
    REFERENCES `mydb`.`Postulacion` (`IDPostulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;







SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
